;; Each new term in the Fibonacci sequence is generated by adding the previous two terms.
;; By starting with 1 and 2, the first 10 terms will be:
;;
;;     1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
;;
;; By considering the terms in the Fibonacci sequence whose values do not exceed
;; four million, find the sum of the even-valued terms.
;;
;; http://projecteuler.net/problem=2
;;
;; Answer: 4613732

(ns dh.euler.solutions.problem_002
  (:use [dh.euler.util.core :refer [fibonacci]]))


(def even-fibs (filter even? fibonacci))

(defn euler-002
  []
  (reduce + (take-while #(< % 4000000)
                        even-fibs)))

