;; The sequence of triangle numbers is generated by adding the natural numbers.
;; So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28.
;; The first ten terms would be:
;;
;; 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
;;
;; Let us list the factors of the first seven triangle numbers:
;;
;;      1: 1
;;      3: 1,3
;;      6: 1,2,3,6
;;     10: 1,2,5,10
;;     15: 1,3,5,15
;;     21: 1,3,7,21
;;     28: 1,2,4,7,14,28
;;
;; We can see that 28 is the first triangle number to have over five divisors.
;;
;; What is the value of the first triangle number to have over five hundred divisors?
;;
;; http://projecteuler.net/problem=12
;;
;; Answer: 76576500

(ns dh.euler.solutions.problem_012
  (:use [dh.euler.util.core :refer [squint factor? factorise]]))


(defstruct tn :num :n)

(defn next-tn
  [tnum]
  (let [n (inc (tnum :n))
        num (+ (tnum :num) n)]
    (struct-map tn :n n :num num)))


(defn euler-012
  []
  (loop [tnum (struct-map tn :num 1 :n 1)]
    (let [num (tnum :num)
          factors (factorise num)]
      (if (> (count factors) 500)
        num
        (recur (next-tn tnum))))))
